service: base-graphql

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    FAUNADB_SECRET: fnACXKFYL9ACAUT-LM0hXL7r5G0GK1oWsL4U7UAg

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: POST
          path: graphql 
          cors: true
